// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-6twhGF15kNh-i2tS-jpsDRbV6a5TId8',
    appId: '1:618190322619:web:4764a71af3939e0ab3229e',
    messagingSenderId: '618190322619',
    projectId: 'kaburlu-a7fa5',
    authDomain: 'kaburlu-a7fa5.firebaseapp.com',
    storageBucket: 'kaburlu-a7fa5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlpiXDO2gsCjiNhJ2X1TUU6pIz898Tc8Y',
    appId: '1:618190322619:android:b41a6b4ca272a1dcb3229e',
    messagingSenderId: '618190322619',
    projectId: 'kaburlu-a7fa5',
    storageBucket: 'kaburlu-a7fa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGJEGuqD5DOexMwjgH6QPqH8ziHZ-T7zw',
    appId: '1:618190322619:ios:bb262dcac0fad3dab3229e',
    messagingSenderId: '618190322619',
    projectId: 'kaburlu-a7fa5',
    storageBucket: 'kaburlu-a7fa5.appspot.com',
    iosBundleId: 'com.example.kaburlu',
  );
}
